let  miNombre= "Matias";
let  miApellido="Calvi";
let  miEdad=23;
let  miMascota="Peter";
let edadMascota=1.3;
let nombreCompleto=miNombre+" "+miApellido;
let textoPresentacion="Hola mi nombre es "+nombreCompleto+" mi edad es de "+miEdad+" mi mascota se llama "+miMascota+" y tiene una edad de "+edadMascota+" años";
let sumaEdades=miEdad+edadMascota;
let restaEdades=miEdad-edadMascota;
let productoEdades=miEdad*edadMascota;
let divisionEdades=miEdad/edadMascota;
console.log(textoPresentacion);
console.log({miNombre,miApellido,miEdad,miMascota,edadMascota});
let alerta=prompt("ingrese su nombre ");
let alertaDos=prompt("ingrese su apellido ");
let alertaTres=prompt("ingrese su edad ");
let alertaCuatro=prompt("ingrese el nombre de su mascota ");
let alertaCinco=prompt("ingrese la edad de su mascota ");
console.log({alerta,alertaDos,alertaTres,alertaCuatro,alertaCinco});
nombreCompleto=alerta+" "+alertaDos;
textoPresentacion="Hola mi nombre es "+nombreCompleto+" mi edad es de "+alertaTres+" mi mascota se llama "+alertaCuatro+" y tiene una edad de "+alertaCinco+" años";
sumaEdades=alertaTres+alertaCinco;
restaEdades=alertaTres-alertaCinco;
productoEdades=alertaTres*alertaCinco;
divisionEdades=alertaTres/alertaCinco;
console.log(textoPresentacion);
